### ISSUE TITLE
unit32_t compilation error

### ISSUE THREAD

**Issue by ntakebay** [bailey-lab/bibseq#1]
I was compiling SeekDeep, which pulled njhseq 3.0.1, and noticed a compilation error (with g++ 14.2.1 from Fedora 40).
It compiles after adding #include <ctdint> to src/njhseq/objects/helperObjects/tandemRepeat.hpp  as the compiler suggested.

```
In file included from src/njhseq/objects/helperObjects/tandemRepeat.cpp:1:
src/njhseq/objects/helperObjects/tandemRepeat.hpp:35:9: error: ‘uint32_t’ does not name a type
   35 |         uint32_t numberOfRepeats_;
      |         ^~~~~~~~
src/njhseq/objects/helperObjects/tandemRepeat.hpp:27:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   26 | #include <string>
  +++ |+#include <cstdint>
   27 | 

```

**Comment by nickjhathaway** [comment]
Thank you for the heads up. It appears that for g++ versions 12 and later the default header includes have changed and <cstdint> was included in <string> or one of the headers in <string> included it. I have changed the code as you pointed out above in the current developmental version to include <cstdint>, I also found a couple of other instances in the code base with similar problems which I have now fixed. A quick fix for the current code would be to compile with g++11 or less
